import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import SessionProvider from '@/app/components/SessionProviders'
import { redirect } from 'next/navigation';
import { AppGetServerSession } from "../api/auth/[...nextauth]/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getServerSession(authOptions); 
  const session = await AppGetServerSession();
  console.log("session na ka",session)
  console.log(session)
  if (!session) {
    return redirect('/');
  }

  return (
      <html lang="en">
      <body className={inter.className}>
      <SessionProvider>
        {children}
      </SessionProvider>
      </body>
     </html> 
      
    
  );
}
